micronaut:
  application:
    name: client
  router:
    static-resources:
      default:
        paths:
         - classpath:public
        mapping: /public/**/*
        enabled: true
datasources:
  default:
    dialect: MYSQL
    url: jdbc:mysql://localhost:3306/testing
    driverClassName: com.mysql.cj.jdbc.Driver
    username: app
    password: app

flyway:
  datasources:
    default:
      enabled: true
      locations:
      - classpath:flyway

netty:
  default:
    allocator:
      max-order: 3
